server:
  port: 8802
spring:
  application:
    name: cloud-stream-rabbitmq-consumer8802
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 192.168.43.102
                port: 5672
                username: admin
                password: admin
      bindings: # 服务的整合处理
        input: # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
          group: queueOne   #分组，防止重复消费
eureka:
  client:
    service-url:
      defaultZone: http://register7001:7001/eureka #单机版
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 5
    instance-id: cloud-stream-rabbitmq  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址

