server:
  port: 8001
spring:
  application:
    name: cloud-hystrix-feign-provider8001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://register7001:7001/eureka #单机版
