spring:
  application:
    name: cloud-gateway-payment9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: cloud-provider-payment8001
          uri: lb://cloud-provider-payment #断言通过后，路由转发的uri
          predicates:    #断言，路径匹配的进行路由
            - Path=/**
            - After=2020-05-01T09:51:17.734+08:00[Asia/Shanghai]  #after表示再这个时间点后才可以匹配
            #            - Cookie=username,zhangsan    #设置cookie中含有username,zhangsan键值对
            - Header=X-Request-Id,\d+   #请求头要有token的正则表达式
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://register7001:7001/eureka/ #单机
  instance:
    instance-id: cloud-gateway-payment9527
    prefer-ip-address: true
server:
  port: 9527
