spring:
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: '0000'
    url: jdbc:mysql:///springclouddb?useUnicode=true&characterEncoding=utf-8&useSSL=false
  application:
    name: cloud-provider-payment
server:
  port: 8001
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: lg.cn.entity
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      #      defaultZone: http://register7002:7002/eureka,http://register7001:7001/eureka
      defaultZone: http://register7001:7001/eureka #单机版
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示ip地址
