server:
  port: 8004
spring:
  application:
    name: cloud-consul-provider-payment8004
  cloud:
    consul:
      host: 192.168.43.102 #consul注册中心地址
      port: 8500
      discovery:
        hostname: 192.168.43.222 #服务的地址
        service-name: ${spring.application.name}


