spring:
  application:
    name: cloud-openfeign-consumer-order80
server:
  port: 80
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://register7001:7001/eureka
    fetch-registry: true
    register-with-eureka: false
ribbon:
  #建立连接所需得时间
  ReadTimeout: 5000
  #建立连接后从服务器获取到资源所用的时间
  ConnectTimeout: 5000
feign:
  client:
    config:
      feignName:
        loggerLevel: full
