server:
  port: 80
spring:
  application:
    name: cloud-hystrix-openfeign-consumer-order80
eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://register7001:7001/eureka #单机版
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
