spring:
  application:
    name: cloud-consumer-order80
server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://register7001:7001/eureka,http://register7002:7002/eureka
    register-with-eureka: true
    fetch-registry: true
